apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  # A URL Mágica: usuario:senha@nome-do-service-do-k8s:porta/nome-do-banco
  DATABASE_URL: "postgresql://postgres:minhasenha123@postgres-service:5432/crypto_db"